### ISSUE TITLE
Crash: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Partonetrain** [IamBlueSlime/LedMC#1]
```
[net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  LoadingPlugin (Quark-r1.4-125.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.4-universal.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b156.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 7/30/18 4:53 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LedMC (ledmc)
Caused by: java.lang.NoClassDefFoundError: com/jgoodies/forms/layout/FormLayout
	at fr.blueslime.ledmc.GuiConfiguration.$$$setupUI$$$(GuiConfiguration.java:113)
	at fr.blueslime.ledmc.GuiConfiguration.<init>(GuiConfiguration.java:98)
	at fr.blueslime.ledmc.LedMC.preInit(LedMC.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:246)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.jgoodies.forms.layout.FormLayout
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 863505184 bytes (823 MB) / 1929379840 bytes (1840 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 125 mods loaded, 125 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version           | Source                                              | Signature                                |
	|:----- |:-------------------------- |:----------------- |:--------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                  | 1.12.2            | minecraft.jar                                       | None                                     |
	| UCH   | mcp                        | 9.42              | minecraft.jar                                       | None                                     |
	| UCH   | FML                        | 8.0.99.99         | forge-1.12.2-14.23.4.2739.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                      | 14.23.4.2739      | forge-1.12.2-14.23.4.2739.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | quarryplus                 | 0.9.8             | AdditionalEnchantedMiner-1.12.2-0.9.8-universal.jar | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| UCH   | advancedmortars            | 1.12.2-1.6.21     | advancedmortars-1.12.2-1.6.21.jar                   | None                                     |
	| UCH   | aether_legacy              | 1.12.2-v3.2       | aether_legacy-1.12.2-v3.2.jar                       | None                                     |
	| UCH   | charset                    | 0.5.3.2           | Charset-Lib-0.5.3.2.jar                             | None                                     |
	| UCH   | jei                        | 4.11.0.202        | jei_1.12.2-4.11.0.202.jar                           | None                                     |
	| UCH   | theoneprobe                | 1.4.23            | theoneprobe-1.12-1.4.23.jar                         | None                                     |
	| UCH   | redstoneflux               | 2.0.2             | RedstoneFlux-1.12-2.0.2.3-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | cofhcore                   | 4.5.3             | CoFHCore-1.12.2-4.5.3.20-universal.jar              | None                                     |
	| UCH   | cofhworld                  | 1.2.0             | CoFHWorld-1.12.2-1.2.0.5-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thermalfoundation          | 2.5.0             | ThermalFoundation-1.12.2-2.5.0.19-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | immersiveengineering       | 0.12-84           | ImmersiveEngineering-0.12-84.jar                    | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | alternatingflux            | 0.12-4            | alternatingflux-0.12-4.jar                          | None                                     |
	| UCH   | appleskin                  | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                          | None                                     |
	| UCH   | aroma1997core              | 2.0.0.0.b156      | Aroma1997Core-1.12.2-2.0.0.0.b156.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCH   | aroma1997sdimension        | 1.3.0.0.b37       | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar   | None                                     |
	| UCH   | ichunutil                  | 7.1.4             | iChunUtil-1.12.2-7.1.4.jar                          | None                                     |
	| UCH   | attachablegrinder          | 7.0.0             | AttachableGrinder-1.12.2-7.0.0.jar                  | None                                     |
	| UCH   | psi                        | r1.1-59           | Psi-r1.1-59.jar                                     | None                                     |
	| UCH   | quark                      | r1.4-125          | Quark-r1.4-125.jar                                  | None                                     |
	| UCH   | autoreglib                 | 1.3-18            | AutoRegLib-1.3-18.jar                               | None                                     |
	| UCH   | badwithernocookiereloaded  | 1.12.2-3.1.14     | badwithernocookiereloaded-1.12.2-3.1.14.jar         | None                                     |
	| UCH   | baubles                    | 1.5.2             | Baubles-1.12-1.5.2.jar                              | None                                     |
	| UCH   | betterthanbunnies          | 1.12.1-1.1.0      | BetterThanBunnies-1.12.1-1.1.0.jar                  | None                                     |
	| UCH   | betterthanllamas           | 1.12.1-1.0.0      | BetterThanLlamas-1.12.1-1.0.0.jar                   | None                                     |
	| UCH   | bibliocraft                | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                   | None                                     |
	| UCH   | bibliotheca                | 1.3.3-1.12.2      | bibliotheca-1.3.3-1.12.2.jar                        | None                                     |
	| UCH   | bonsaitrees                | 1.0.5             | bonsaitrees-1.0.5-b77.jar                           | None                                     |
	| UCH   | bookshelf                  | 2.3.552           | Bookshelf-1.12.2-2.3.552.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | botania                    | r1.10-354         | Botania r1.10-354.jar                               | None                                     |
	| UCH   | bottledmilk                | 1.0.0             | BottledMilk-1.12-1.1.0.jar                          | None                                     |
	| UCH   | buildinggadgets            | 1.6.2             | BuildingGadgets-1.6.2.jar                           | None                                     |
	| UCH   | ceramics                   | 1.12-1.3.4        | Ceramics-1.12-1.3.4.jar                             | None                                     |
	| UCH   | cfb                        | 1.0               | cfb-1.0.jar                                         | None                                     |
	| UCH   | chameleon                  | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                            | None                                     |
	| UCH   | chargers                   | 1.0.0             | Chargers-1.12.2-1.0.0.1.jar                         | 58e787c8aafad8b327883f94d4fa544f936d7b01 |
	| UCH   | ctm                        | MC1.12.2-0.3.2.18 | CTM-MC1.12.2-0.3.2.18.jar                           | None                                     |
	| UCH   | chisel                     | MC1.12.2-0.2.0.31 | Chisel-MC1.12.2-0.2.0.31.jar                        | None                                     |
	| UCH   | chiselsandbits             | 14.20             | chiselsandbits-14.20.jar                            | None                                     |
	| UCH   | codechickenlib             | 3.2.1.349         | CodeChickenLib-1.12.2-3.2.1.349-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | cyclopscore                | 0.11.8            | CyclopsCore-1.12.2-0.11.8.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | colossalchests             | 1.6.11            | ColossalChests-1.12.2-1.6.11.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | controlling                | 3.0.6             | Controlling-3.0.6.jar                               | None                                     |
	| UCH   | crafttweaker               | 4.1.9             | CraftTweaker2-1.12-4.1.9.jar                        | None                                     |
	| UCH   | ctgui                      | 1.0.0             | CraftTweaker2-1.12-4.1.9.jar                        | None                                     |
	| UCH   | crafttweakerjei            | 2.0.2             | CraftTweaker2-1.12-4.1.9.jar                        | None                                     |
	| UCH   | cttinycoal                 | 1.12.2-1.0.2      | cttinycoal-1.12.2-1.0.2.jar                         | None                                     |
	| UCH   | mantle                     | 1.12-1.3.2.24     | Mantle-1.12-1.3.2.24.jar                            | None                                     |
	| UCH   | p455w0rdslib               | 2.0.32            | p455w0rdslib-1.12-2.0.32.jar                        | None                                     |
	| UCH   | danknull                   | 1.4.33            | DankNull-1.12-1.4.33.jar                            | None                                     |
	| UCH   | defaultworldgenerator-port | 1.12-2.3          | DefaultWorldGenerator-port-1.12-2.3.jar             | None                                     |
	| UCH   | dropchevsky                | b16               | dropchevsky-b16.jar                                 | None                                     |
	| UCH   | emberroot                  | 1.3.8             | EmberRootZoo-1.12.2-1.3.8.jar                       | None                                     |
	| UCH   | enablecheats               | @MODVERSION@      | EnableCheats-1.12.2-1.0.0.jar                       | None                                     |
	| UCH   | endercompass               | 1.2.6.1           | EnderCompass-1.12-1.2.6.1.jar                       | None                                     |
	| UCH   | enderstorage               | 2.4.5.135         | EnderStorage-1.12.2-2.4.5.135-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | energeticsheep             | 1.1.2             | EnergeticSheep-1.12.2-1.1.2.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | shadowmc                   | 3.8.0             | ShadowMC-1.12-3.8.0.jar                             | None                                     |
	| UCH   | extrarails                 | 1.3.0             | ExtraRails-1.12-1.3.0.jar                           | None                                     |
	| UCH   | ezstorage                  | 2.5.0             | ezstorage-2.5.0-[1.12.2].jar                        | None                                     |
	| UCH   | fairylights                | 2.1.2             | fairylights-2.1.2-1.12.x.jar                        | None                                     |
	| UCH   | flopper                    | 1.0.2             | Flopper-1.12.2-1.0.2.jar                            | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | forgelin                   | 1.7.4             | Forgelin-1.7.4.jar                                  | None                                     |
	| UCH   | mcmultipart                | 2.5.1             | MCMultiPart-2.5.1.jar                               | None                                     |
	| UCH   | ftblib                     | 5.2.0.28          | FTBLib-5.2.0.28.jar                                 | None                                     |
	| UCH   | journeymap                 | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                         | None                                     |
	| UCH   | ftbutilities               | 5.2.0.33          | FTBUtilities-5.2.0.33.jar                           | None                                     |
	| UCH   | gps                        | 3.1.1.2           | GPS-1.12.2-3.1.1.2.jar                              | None                                     |
	| UCH   | grapplemod                 | 1.12.2-v10        | grapplemod-v10-1.12.2.jar                           | None                                     |
	| UCH   | harvest                    | 1.12-1.2.6-18     | Harvest-1.12-1.2.6-18.jar                           | None                                     |
	| UCH   | hopperducts                | 1.5               | hopperducts-mc1.12-1.5.jar                          | None                                     |
	| UCH   | horseinfo                  | 1.0.1             | horseinfo-1.0.1.jar                                 | None                                     |
	| UCH   | horsetweaks                | 1.0.4             | HorseTweaks_1.12.2-1.0.4.jar                        | None                                     |
	| UCH   | hoverboard                 | GRADLE:VERSION    | hoverboard-1.3.jar                                  | None                                     |
	| UCH   | immersivepetroleum         | 1.1.9             | immersivepetroleum-1.12.2-1.1.9.jar                 | None                                     |
	| UCH   | inspirations               | 1.12.2-0.2.1      | Inspirations-1.12.2-0.2.1.jar                       | None                                     |
	| UCH   | inventorysorter            | 1.13.3+57         | inventorysorter-1.12.2-1.13.3+57.jar                | None                                     |
	| UCH   | itank                      | 1.2.0-1.12.2      | ITank-1.2.0-1.12.2.jar                              | None                                     |
	| UCH   | itemscroller               | 0.12.0            | itemscroller-1.12.2-0.12.0.jar                      | 2b03e1423915a189b8094816baa18f239d576dff |
	| UCH   | jeresources                | 0.8.5.27          | JustEnoughResources-1.12.2-0.8.5.27.jar             | None                                     |
	| UCEE  | ledmc                      | ${version}        | LedMC-1.0.0.jar                                     | None                                     |
	| UC    | lostcities                 | 2.0.10            | lostcities-1.12-2.0.10.jar                          | None                                     |
	| UC    | lostsouls                  | 1.1.4             | lostsouls-1.12-1.1.4.jar                            | None                                     |
	| UC    | magipsi                    | 1.3               | MagicalPsi-1.3.jar                                  | None                                     |
	| UC    | malisiscore                | 1.12.2-6.4.0      | malisiscore-1.12.2-6.4.0.jar                        | None                                     |
	| UC    | malisisdoors               | 1.12.2-7.3.0      | malisisdoors-1.12.2-7.3.0.jar                       | None                                     |
	| UC    | mcjtylib_ng                | 3.0.3             | mcjtylib-1.12-3.0.3.jar                             | None                                     |
	| UC    | morpheus                   | 1.12-3.3.2        | Morpheus-1.12-3.3.2.jar                             | None                                     |
	| UC    | naturescompass             | 1.5.1             | NaturesCompass-1.12.2-1.5.1.jar                     | None                                     |
	| UC    | neat                       | 1.4-16            | Neat 1.4-16.jar                                     | None                                     |
	| UC    | netherportalfix            | 5.3.13            | NetherPortalFix_1.12.1-5.3.13.jar                   | None                                     |
	| UC    | notenoughwands             | 1.7.0             | notenoughwands-1.12-1.7.0.jar                       | None                                     |
	| UC    | oreexcavation              | 1.4.119           | OreExcavation-1.4.119.jar                           | None                                     |
	| UC    | oeintegration              | 2.3.3             | oeintegration-2.3.3.jar                             | None                                     |
	| UC    | openglider                 | @VERSION@         | OpenGlider-1.12.1-1.1.0.jar                         | None                                     |
	| UC    | placebo                    | 1.4.0             | Placebo-1.12.2-1.4.0.jar                            | None                                     |
	| UC    | shetiphiancore             | 3.5.7             | shetiphiancore-1.12.0-3.5.7.jar                     | None                                     |
	| UC    | platforms                  | 1.4.5             | platforms-1.12.0-1.4.5.jar                          | None                                     |
	| UC    | portalgun                  | 7.0.2             | PortalGun-1.12.2-7.0.2.jar                          | None                                     |
	| UC    | quickleafdecay             | 1.2.4             | QuickLeafDecay-MC1.12.1-1.2.4.jar                   | None                                     |
	| UC    | rustic                     | 1.0.6             | rustic-1.0.6.jar                                    | None                                     |
	| UC    | scavenge                   | 1.8               | Scavenge V1.12-1.8.3.1.jar                          | None                                     |
	| UC    | sereneseasons              | 1.2.4             | SereneSeasons-1.12.2-1.2.4-universal.jar            | None                                     |
	| UC    | silentlib                  | 2.3.12            | SilentLib-1.12.2-2.3.12-129.jar                     | None                                     |
	| UC    | silentgems                 | 2.7.7             | SilentsGems-1.12.2-2.7.7-279.jar                    | None                                     |
	| UC    | sgextraparts               | 1.4.1             | SGExtraParts-1.12-1.4.1-34.jar                      | None                                     |
	| UC    | simplecorn                 | 2.4.1             | SimpleCorn1.12-1.12-2.4.1.jar                       | None                                     |
	| UC    | snad                       | 1.12.1-1.7.09.16a | Snad-1.12.1-1.7.09.16a.jar                          | None                                     |
	| UC    | s                          | 1.0               | spikey-1.0.0.jar                                    | None                                     |
	| UC    | toastcontrol               | 1.7.0             | Toast Control-1.12.2-1.7.0.jar                      | None                                     |
	| UC    | tombmanygraves2api         | 1.12.2-1.0.0      | tombmanygraves2api-1.12.2-1.0.0.jar                 | None                                     |
	| UC    | tombmanygraves             | 1.12-4.1.0        | TombManyGraves-1.12-4.1.0.jar                       | None                                     |
	| UC    | topaddons                  | 1.12.2-1.8.0      | topaddons-1.12.2-1.8.0.jar                          | None                                     |
	| UC    | torched                    | 7.0.0             | Torched-1.12.2-7.0.0.jar                            | None                                     |
	| UC    | traverse                   | 1.5.5             | Traverse-1.12.2-1.5.5-65.jar                        | None                                     |
	| UC    | usefulnullifiers           | 1.5.0             | usefulnullifiers-1.5.0.jar                          | None                                     |
	| UC    | va                         | 1.12.2-1.5.3      | va-1.12.2-1.5.4.jar                                 | None                                     |
	| UC    | wanionlib                  | 1.12.2-1.5        | WanionLib-1.12.2-1.5.jar                            | None                                     |
	| UC    | waystones                  | 4.0.53            | Waystones_1.12.2-4.0.53.jar                         | None                                     |
	| UC    | worldstripper              | 1.5.1-1.12.2      | World-Stripper-1.5.1-1.12.2.jar                     | None                                     |
	| UC    | yabba                      | 1.1.2.13          | YABBA-1.1.2.13.jar                                  | None                                     |
	| UC    | unidict                    | 1.12.2-2.5f       | UniDict-1.12.2-2.5f.jar                             | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Quark-r1.4-125.jar)
  vazkii.quark.base.asm.ClassTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.4-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b156.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- TheOneProbePlugin (Enabled/Not Forced)
```

The full log: 
[crash-2018-07-30_16.53.22-client.txt](https://github.com/IamBlueSlime/LedMC/files/2243022/crash-2018-07-30_16.53.22-client.txt)

Looks like a forgotten library.

**Comment by jeremylvln** [comment]
wat

It works with me, time to investigate :)

**Comment by jeremylvln** [comment]
I've uploaded a new Beta release on Curseforge, it should be fixed, thanks :)
